// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvrxwkyilhbhbaoxfvyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12cnh3a3lpbGhiaGJhb3hmdnlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5OTY0MTYsImV4cCI6MjA3MTU3MjQxNn0.Ohw0P7MLTdgpjzWAweBwIMtifi4A1EIeubHem9qZEo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});